"""
Django settings for pickroww project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from django.urls import reverse_lazy
import dj_database_url
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$hs$hs$hs'
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ["pickrow.net", "https://pickrow.net", "www.pickrow.net", "https://pickrow.iran.liara.run"]
ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'unfold',  # before django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dashboard.apps.DashboardConfig',
    'web.apps.WebConfig',
    'rest_framework',
    'heroicons',
    'compressor',
    'import_export'

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pickroww.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            # 'loaders': [
            #     'django.template.loaders.filesystem.Loader',
            #     'django.template.loaders.app_directories.Loader',
            # ],
            'builtins': [
                'heroicons.templatetags.heroicons',
            ],
        },
    },
]

WSGI_APPLICATION = 'pickroww.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# DATABASES = {'default': dj_database_url.config(default='postgresql://root:mULtKDYjlj3dHuiXAUk4l9kh@pickrowdb:5432/postgres')}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Tailwind settings

TAILWIND_APP_NAME = "theme"
INTERNAL_IPS = ["127.0.0.1"]  
NPM_BIN_PATH = r"C:\Program Files\nodejs\npm.cmd"




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'staticfiles'),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Unfold settings
UNFOLD = {
    "SITE_TITLE": "PickRow",
    "SITE_HEADER": "PickRow",
    "SITE_URL": "/",
    "SITE_ICON": True,
    "SITE_LOGO": "http://127.0.0.1:8000/static/images/PickRow.png",
    "DASHBOARD_CALLBACK": "dashboard.views.dashboard_callback",
    "BORDER_RADIUS": "16px",
    # "COLORS": {
    #     "secondary": {
    #         "50": "248 250 252",
    #         "100": "241 245 249",
    #         "200": "226 232 240",
    #         "300": "203 213 225",
    #         "400": "148 163 184",
    #         "500": "100 116 139",
    #         "600": "71 85 105",
    #         "700": "51 65 85",
    #         "800": "30 41 59",
    #         "900": "15 23 42",
    #         "950": "2 6 23",
    #     },
    #     "primary": {
    #         #F1F5F9
    #         "50": "255 255 255",
    #         "100": "222 233 233",
    #         "200": "188 211 209",
    #         "300": "147 181 181",
    #         "400": "108 148 149",
    #         "500": "82 120 122",
    #         "600": "45 72 63",
    #         "700": "54 77 79",
    #         "800": "46 63 65",
    #         "900": "41 55 56",
    #         "950": "20 29 31",
    #     },
    # },
    "EXTENSIONS": {
        "SECTIONS": True,
    },
    "SIDEBAR": {
        "font_size": "26px",
        "show_search": True,
        "show_all_applications": True,
        "show_history": True,
        "show_view_on_site": True,
        "navigation": [
            {
                "title": "Menu",
                "items": [
                    {
                        "title": "Home",
                        "link": "/admin/",
                        "icon": "home",
                    },
                    {
                        "title": "Products",
                        "link": reverse_lazy('admin:dashboard_category_changelist'),
                        "icon": "archive-box",
                    },
                    {
                        "title": "Customers",
                        "link": reverse_lazy('admin:dashboard_buyer_changelist'),
                        "icon": "user-group",
                    },
                    {
                        "title": "Reports",
                        "link": "/admin/reports/",
                        "icon": "chart-bar",
                    },
                    {
                        "title": "Map",
                        "link": "/admin/map/",
                        "icon": "map",
                    },
                    {
                        "title": "Users",
                        "link": "/admin/auth/user/",
                        "icon": "user-plus",
                    },
                ],
            },
        ],
    },
}

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',
        'user': '1000/day',
        'product_code_check': '5/minute',
    }
}


COMPRESS_ROOT = BASE_DIR / 'staticfiles'

COMPRESS_ENABLED = True

STATICFILES_FINDERS = ('compressor.finders.CompressorFinder',)